export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_LISTS_UPDATE = 'REQUEST_LISTS_UPDATE';

export const REQUEST_LISTS_DELETE = 'REQUEST_LISTS_DELETE';

export const REQUEST_LISTS_EDIT = 'REQUEST_LISTS_EDIT';

export const REQUEST_LISTS_COMPLETED = 'REQUEST_LISTS_COMPLETED'